// Profile Data
export const profile = {
    name: 'Fatih Maulana',
    title: 'Forward Deployed Engineer & Researcher',
    email: 'fatihmaulanamail@gmail.com',
    phone: '+62 896-1846-5959',
    location: 'Bandung, Indonesia',
    bio: 'Engineer and researcher at the intersection of distributed systems, applied cryptography, and AI. Forward Deployed Engineer solving end-to-end business problems with technology and AI; shipped production apps for SMEs and early-stage startups since 2024. First-author research in post-quantum cryptography for high-throughput blockchains and blockchain supply-chain traceability (gold medal). Grant-funded Stellar open-source contributor; build experience on Solana and Base. Security practice: ISO 27001/SOC 2 audit support, penetration testing, smart contract review.',
    socials: {
        github: 'https://github.com/Fatihmaull',
        linkedin: 'https://linkedin.com/in/fatihmaulana',
        zenodo: 'https://zenodo.org/records/18096724',
        email: 'mailto:fatihmaulanamail@gmail.com',
        whatsapp: 'https://wa.me/6289618465959',
    },
};

// Navigation Items
export const navItems = [
    { name: 'About', href: '/#about' },
    { name: 'Works', href: '/#experience' },
    { name: 'Blog', href: '/blog/' },
    { name: 'Gallery', href: '/gallery' },
    { name: 'Contact', href: '/contact' },
];

// Physics Hero Skill Tags
export const skillTags = [
    'Distributed Systems',
    'Cryptography',
    'Python',
    'TypeScript',
    'Rust',
    'Solidity',
    'Next.js',
    'Security',
];

// Projects for Bento Grid. Featured list first, then the rest.
// Items without a confirmed URL keep the existing placeholder href.
export const projects = [
    {
        id: 1,
        title: 'Evergreen',
        description: 'Open-source Soroban TTL and state-archival automation. Stellar Community Fund Instaward.',
        tags: ['Soroban', 'Stellar', 'TTL'],
        size: 'large',
        featured: true,
        link: 'https://github.com/Fatihmaull/evergreen',
    },
    {
        id: 2,
        title: 'HalalChain',
        description: 'Trustless batch traceability on Base L2. First author; gold medal, ICYMS 2026.',
        tags: ['Base', 'Solidity', 'Next.js'],
        size: 'vertical',
        link: 'https://halal-chain-tawny.vercel.app',
    },
    {
        id: 3,
        title: 'ARES',
        description: 'Agentic AI platform (Hermes workflow) for vulnerability detection in Solana smart contracts. Daemon Protocol.',
        tags: ['Solana', 'AI', 'Security'],
        size: 'square',
        link: 'https://ares-web-xi.vercel.app',
    },
    {
        id: 4,
        title: 'Parity',
        description: 'Every PreStock on Solana, priced correctly. Stocklana hackathon, PreStocks bounty.',
        tags: ['Solana'],
        size: 'square',
        link: 'https://parity-khaki-pi.vercel.app',
    },
    {
        id: 5,
        title: 'FOCU Studio',
        description: 'Web agency. CI/CD with Cloudflare Tunnel and GitHub Actions.',
        tags: ['CI/CD', 'Cloudflare', 'GitHub Actions'],
        size: 'wide',
        link: 'https://focustudio.online',
    },
    {
        id: 6,
        title: 'parkir-bpm',
        description: 'Offline-first multi-tenant smart gate and parking system. Edge/hardware, payments, and sync.',
        tags: ['Edge', 'Payments', 'Sync'],
        size: 'square',
        link: 'https://github.com/Fatihmaull/parkir-bpm',
    },
    {
        id: 7,
        title: 'zcash-multisig',
        description: 'FROST shared custody for Zcash shielded funds. Colosseum Crypto World\'s Fair, Zcash track.',
        tags: ['Zcash', 'FROST'],
        size: 'square',
        link: 'https://github.com/Fatihmaull/zcash-multisig',
    },
    {
        id: 8,
        title: 'Nemesis Protocol',
        description: 'Founding Engineer and BD. EV financing rails, on-chain settlement, and IoT/DePIN data. 2026.',
        tags: ['Solana', 'DePIN', 'IoT'],
        size: 'square',
        link: '#',
    },
    {
        id: 9,
        title: 'Ormawa ERP',
        description: 'ERP for student organizations, Next.js and Supabase.',
        tags: ['Next.js', 'Supabase'],
        size: 'square',
        link: 'https://ormawa-erp.vercel.app',
    },
    {
        id: 11,
        title: 'Apex on Stellar',
        description: 'APAC compute marketplace.',
        tags: ['Stellar'],
        size: 'square',
        link: 'https://github.com/Fatihmaull/apex-on-stellar',
    },
    {
        id: 15,
        title: 'Auditorum',
        description: 'Web3 audit framework and blockchain report verification. Feb 2026.',
        tags: ['Web3', 'Audit'],
        size: 'square',
        link: 'https://auditorum-inky.vercel.app',
    },
    {
        id: 16,
        title: 'Freelance DeFi Stability Platform',
        description: 'Solana, Rust, stablecoins, and a micro-task collateral engine. Jan 2026.',
        tags: ['Solana', 'Rust', 'Stablecoins'],
        size: 'square',
        link: '#',
    },
    {
        id: 17,
        title: 'BrandkinAI',
        description: 'Mascot and identity generator.',
        tags: ['AI'],
        size: 'square',
        link: 'https://brandkin-ai.vercel.app',
    },
    {
        id: 18,
        title: 'Rivalry',
        description: '',
        tags: [],
        size: 'square',
        link: 'https://rivalry-ashy.vercel.app',
    },
    {
        id: 20,
        title: 'DIY Brain-Computer Interface',
        description: 'ESP32 and C++, with band-pass and notch filters. Dec 2025.',
        tags: ['ESP32', 'C++'],
        size: 'square',
        link: '#',
    },
    {
        id: 21,
        title: 'E-commerce Penetration Testing',
        description: 'Burp Suite and OWASP ZAP. XSS, IDOR, and broken access control; CVSS reports. Jan 2025.',
        tags: ['Burp Suite', 'OWASP ZAP'],
        size: 'square',
        link: '#',
    },
    {
        id: 22,
        title: 'Dijkstra Pathfinding Visualizer',
        description: 'Java pathfinding visualizer. Jan 2024.',
        tags: ['Java'],
        size: 'square',
        link: 'https://github.com/Fatihmaull/DjikstraMap1',
    },
    {
        id: 23,
        title: 'Embedded IoT Item Counter',
        description: 'C and Arduino. Jan 2024.',
        tags: ['C', 'Arduino'],
        size: 'square',
        link: '#',
    },
    {
        id: 24,
        title: 'Java Banking Simulation',
        description: 'Banking simulation with deposit, withdrawal, and investment, using OOP. Jan 2023.',
        tags: ['Java', 'OOP'],
        size: 'square',
        link: 'https://github.com/Fatihmaull/BANK-DASPRO',
    },
    {
        id: 25,
        title: 'StudentxCEOs Website',
        description: 'Landing page with login and registration in Next.js and TypeScript.',
        tags: ['Next.js', 'TypeScript'],
        size: 'square',
        link: '#',
    },
    {
        id: 26,
        title: 'Mobile E-commerce Prototype',
        description: 'Functional prototype in Flutter (Dart), focused on state management.',
        tags: ['Flutter', 'Dart'],
        size: 'square',
        link: '#',
    },
    {
        id: 27,
        title: 'Campus Whistle-blowing System',
        description: 'CRUD reporting system in PHP and MySQL.',
        tags: ['PHP', 'MySQL'],
        size: 'square',
        link: '#',
    },
    {
        id: 28,
        title: 'Psychology-based Game',
        description: 'Game prototype in Unity and C#.',
        tags: ['Unity', 'C#'],
        size: 'square',
        link: '#',
    },
    {
        id: 29,
        title: 'Library Management System',
        description: 'Java desktop app for book loans and members.',
        tags: ['Java'],
        size: 'square',
        link: '#',
    },
    {
        id: 10,
        title: 'Kivo on Stellar',
        description: '',
        tags: ['Stellar'],
        size: 'square',
        link: 'https://kivo-on-stellar.vercel.app',
    },
    {
        id: 12,
        title: 'masjidOS',
        description: '',
        tags: [],
        size: 'square',
        link: 'https://masjid-os-omega.vercel.app',
    },
    {
        id: 13,
        title: 'Haji-Umrah',
        description: '',
        tags: [],
        size: 'square',
        link: 'https://haji-umrah.vercel.app',
    },
    {
        id: 14,
        title: 'Bandung Builders',
        description: '',
        tags: [],
        size: 'square',
        link: 'https://presentations-pi-blue.vercel.app',
    },
    {
        id: 19,
        title: 'pokertunity',
        description: '',
        tags: [],
        size: 'square',
        link: 'https://github.com/Fatihmaull/pokertunity',
    },
];

// Blog Post Metadata
export const blogPosts = [
    {
        slug: 'vqc-higgs-boson-detection',
        title: 'Implementing Variational Quantum Classifiers (VQC) for Higgs Boson Signal Detection',
        description: 'A deep dive into VQC implementation for particle physics classification using Qiskit.',
        date: '2026-01-15',
        tags: ['Quantum Computing', 'Research', 'Qiskit'],
        readTime: '12 min',
    },
    {
        slug: 'bitcoin-emh-quantitative-analysis',
        title: 'Why Technical Analysis Failed on Bitcoin: A Quantitative Test of the Efficient Market Hypothesis',
        description: 'Statistical analysis of Bitcoin market efficiency using ROC curves and AUC metrics.',
        date: '2026-01-10',
        tags: ['Quantitative Finance', 'Python', 'Research'],
        readTime: '10 min',
    },
    {
        slug: 'serverless-voting-system-case-study',
        title: 'Salvaging a National Voting System: From Crash to Serverless in 24 Hours',
        description: 'A case study on rapid system recovery and fraud prevention.',
        date: '2026-01-05',
        tags: ['Cybersecurity', 'Case Study', 'Google Apps Script'],
        readTime: '8 min',
    },
    {
        slug: 'diy-bci-esp32-tutorial',
        title: 'Building a Low-Cost Brain-Computer Interface (BCI) with ESP32 and C++',
        description: 'Tutorial on creating an affordable BCI system using embedded hardware.',
        date: '2025-12-28',
        tags: ['Hardware', 'ESP32', 'C++', 'Tutorial'],
        readTime: '15 min',
    },
    {
        slug: 'grc-automation-vanta-iso27001',
        title: 'Automating GRC Compliance: How I Achieved 100% Policy Adherence with Vanta',
        description: 'Practical guide to automating governance, risk, and compliance workflows.',
        date: '2025-12-20',
        tags: ['Cybersecurity', 'GRC', 'Automation'],
        readTime: '9 min',
    },
    {
        slug: 'dijkstra-algorithm-visualization-java',
        title: "Visualizing Dijkstra's Algorithm: Optimizing Graph Theory in Java",
        description: 'Interactive visualization of pathfinding algorithms with Java implementation.',
        date: '2025-12-15',
        tags: ['Algorithms', 'Java', 'Visualization'],
        readTime: '11 min',
    },
    {
        slug: 'secure-api-microservices',
        title: 'Secure API Architecture: Documenting Microservices for Fintech',
        description: 'Best practices for designing secure and well-documented APIs.',
        date: '2025-12-10',
        tags: ['API Design', 'Security', 'Fintech'],
        readTime: '7 min',
    },
    {
        slug: 'web-penetration-testing-guide',
        title: 'Web Penetration Testing Guide: Common Vulnerabilities in E-Commerce (XSS & IDOR)',
        description: 'Comprehensive guide to identifying and mitigating web vulnerabilities.',
        date: '2025-12-05',
        tags: ['Cybersecurity', 'Penetration Testing', 'Tutorial'],
        readTime: '14 min',
    },
    {
        slug: 'scalable-iot-django-mysql',
        title: 'Designing Scalable IoT Backends with Django and MySQL',
        description: 'Architecture patterns for handling high-volume sensor data.',
        date: '2025-11-28',
        tags: ['IoT', 'Django', 'Backend'],
        readTime: '10 min',
    },
    {
        slug: 'physics-to-finance-trading',
        title: 'From Physics to Finance: Applying Scientific Computing in High-Frequency Trading',
        description: 'How physics and computational methods translate to quantitative finance.',
        date: '2025-11-20',
        tags: ['Quantitative Finance', 'Physics', 'Research'],
        readTime: '13 min',
    },
    {
        slug: 'rivalry-mobile-app',
        title: 'Gamifying Personal Growth: Building the Rivalry Mobile App',
        description: 'A case study on developing a cross-platform mobile application for personal challenges using Flutter and Dart.',
        date: '2026-01-18',
        tags: ['Mobile Dev', 'Flutter', 'Dart', 'UX Design'],
        readTime: '8 min',
    },
    {
        slug: 'neural-network-visualizer',
        title: 'Peeking Inside the Black Box: A Neural Network Visualizer',
        description: 'Building an interactive web tool to visualize activation layers in real-time training sessions using React and D3.js.',
        date: '2026-01-20',
        tags: ['Machine Learning', 'React', 'D3.js', 'Visualization'],
        readTime: '10 min',
    },
    {
        slug: 'defi-liquidity-aggregator',
        title: 'Solving Slippage: Engineering a DeFi Liquidity Aggregator',
        description: 'Optimizing trade execution across multiple decentralized exchanges (DEXs) using smart contracts and graph algorithms.',
        date: '2026-01-12',
        tags: ['Blockchain', 'Solidity', 'Web3.js', 'DeFi'],
        readTime: '14 min',
    },
    {
        slug: 'satellite-imagery-analysis',
        title: 'Mapping the Earth: Satellite Imagery Analysis with PyTorch',
        description: 'Using Convolutional Neural Networks (CNNs) to classify land usage patterns from Sentinel-2 satellite data.',
        date: '2026-01-08',
        tags: ['Computer Vision', 'PyTorch', 'Geospatial', 'GIS'],
        readTime: '11 min',
    },
    {
        slug: 'encrypted-chat-protocol',
        title: 'Trust No One: Designing an Encrypted Chat Protocol',
        description: 'Implementing the Double Ratchet Algorithm in Rust to build a secure, forward-secrecy compliant messaging application.',
        date: '2026-01-03',
        tags: ['Cryptography', 'Rust', 'Networking', 'Security'],
        readTime: '15 min',
    },
    {
        slug: 'high-frequency-trading-bot',
        title: 'The Microsecond Race: C++ High-Frequency Trading Bot',
        description: 'Engineering a low-latency market making system for crypto exchanges using C++ and WebSockets.',
        date: '2025-12-30',
        tags: ['Quant', 'C++', 'WebSocket', 'Finance'],
        readTime: '13 min',
    },
    {
        slug: 'generative-art-engine',
        title: 'Chaos & Code: A Generative Art Engine',
        description: 'Exploring algorithmic beauty through Perlin noise, flow fields, and particle systems using p5.js and WebGL.',
        date: '2025-12-25',
        tags: ['Creative Coding', 'p5.js', 'WebGL', 'Art'],
        readTime: '7 min',
    },
    {
        slug: 'distributed-file-system',
        title: 'Reinventing Storage: Building a Distributed File System in Go',
        description: 'Implementing a fault-tolerant, sharded storage system inspired by GFS and HDFS using Go.',
        date: '2025-12-18',
        tags: ['Systems', 'Go', 'Distributed Systems', 'Backend'],
        readTime: '16 min',
    },
    {
        slug: 'smart-home-hub',
        title: 'The Universal Translator: Creating a Smart Home Hub',
        description: 'Unifying fragmented IoT protocols (Zigbee, Z-Wave, WiFi) into a single controlled gateway using Node.js and MQTT.',
        date: '2025-12-12',
        tags: ['IoT', 'Node.js', 'MQTT', 'Hardware'],
        readTime: '11 min',
    },
    {
        slug: 'quantum-key-distribution',
        title: 'Unbreakable Encryption: Simulating Quantum Key Distribution (BB84)',
        description: 'A Python-based simulation of the BB84 protocol demonstrating how quantum mechanics guarantees secure communication.',
        date: '2025-12-08',
        tags: ['Quantum', 'Python', 'Education', 'Cryptography'],
        readTime: '12 min',
    },
    {
        slug: 'bioinformatics-dna-sequencer',
        title: 'Decoading Life: High-Performance DNA Sequence Alignment',
        description: 'Accelerating the Smith-Waterman algorithm for FASTQ DNA sequence alignment using C++ and OpenMP parallelization.',
        date: '2025-12-02',
        tags: ['Bioinformatics', 'C++', 'OpenMP', 'Algorithms'],
        readTime: '14 min',
    },
    {
        slug: 'technical-documentation-system',
        title: 'Building a Technical Documentation System: From Code to User Manuals',
        description: 'Creating comprehensive documentation frameworks for microservices architecture, including role-based user manuals and system documentation.',
        date: '2025-11-15',
        tags: ['Technical Writing', 'Documentation', 'GitLab', 'Notion'],
        readTime: '9 min',
    },
    {
        slug: 'sentiment-analysis-svm',
        title: 'User Sentiment Analysis with Support Vector Machines',
        description: 'Implementing SVM-based sentiment analysis for product insights and user feedback processing.',
        date: '2025-11-10',
        tags: ['Machine Learning', 'SVM', 'NLP', 'Python'],
        readTime: '11 min',
    },
    {
        slug: 'microservices-api-documentation',
        title: 'Documenting Microservices: API Contracts and Service Boundaries',
        description: 'Best practices for documenting API contracts and service boundaries in distributed microservices architectures.',
        date: '2025-11-05',
        tags: ['API Design', 'Microservices', 'Documentation', 'Architecture'],
        readTime: '8 min',
    },
    {
        slug: 'code-quality-monitoring',
        title: 'Proactive Bug Detection: Code Quality Monitoring with SonarQube and Grafana',
        description: 'Setting up automated code quality analysis and application log monitoring for early bug detection.',
        date: '2025-10-30',
        tags: ['DevOps', 'SonarQube', 'Grafana', 'Monitoring'],
        readTime: '10 min',
    },
    {
        slug: 'nextjs-ssr-optimization',
        title: 'Optimizing Next.js Server-Side Rendering: Performance Tips and Tricks',
        description: 'Resolving SSR performance issues and optimizing component rendering for faster page loads in Next.js applications.',
        date: '2025-10-25',
        tags: ['Next.js', 'Performance', 'SSR', 'React'],
        readTime: '7 min',
    },
    {
        slug: 'cicd-github-actions-cloudflare',
        title: 'Automated Deployment: CI/CD with GitHub Actions and Cloudflare Tunnel',
        description: 'Building reliable CI/CD pipelines using GitHub Actions and Cloudflare Tunnel for automated deployment workflows.',
        date: '2025-10-20',
        tags: ['CI/CD', 'GitHub Actions', 'Cloudflare', 'DevOps'],
        readTime: '9 min',
    },
    {
        slug: 'virtual-event-infrastructure',
        title: 'Scaling Virtual Events: Infrastructure for National-Level Scholarship Selection',
        description: 'Designing scalable virtual infrastructure with secure access controls for large-scale online events and interviews.',
        date: '2025-10-15',
        tags: ['Infrastructure', 'Virtual Events', 'Zoom', 'Security'],
        readTime: '8 min',
    },
];

// Work Experiences (ordered by most recent first)
export const experiences = [
    {
        id: 1,
        role: 'Project Manager Intern',
        company: 'Ibunda.id',
        location: 'Bandung, Indonesia (Hybrid)',
        period: 'Oct 2026 — Apr 2027',
        description: [],
        tags: [],
    },
    {
        id: 2,
        role: 'Forward Deployed Engineer & Product Owner',
        company: 'Daemon Protocol',
        location: 'Remote',
        period: 'Apr 2026 — Present',
        description: [
            'Embedded with clients from discovery through production delivery, solving end-to-end business problems with technology and AI.',
            'Leads Ares, an agentic AI platform using the Hermes workflow for vulnerability detection in Solana smart contracts.',
            'Fine-tunes LLMs on malware and vulnerability datasets.',
            'Leads a paper on AI agents finding flaws in the Solana Sealevel runtime.',
        ],
        tags: ['Solana', 'AI', 'Security'],
    },
    {
        id: 3,
        role: 'City Builders Lead',
        company: 'BlockDev.ID',
        location: 'Bandung',
        period: 'Jun 2026 — Jul 2026',
        description: [
            'Led a 1-month Web3 incubator in Bandung and mentored 15 developers building DeFi MVPs.',
            'Delivered an EVM curriculum on Solidity, Foundry, and Wagmi/Next.js on Base L2.',
            'Guided teams from system architecture and tokenomics through go-to-market and pitches.',
        ],
        tags: ['Solidity', 'Foundry', 'Base', 'Next.js'],
    },
    {
        id: 4,
        role: 'Instaward Awardee, Developer Tooling',
        company: 'Stellar Development Foundation (Stellar Community Fund)',
        location: 'Remote',
        period: '2026',
        description: [
            'Awarded USD 4,800 in XLM to build Evergreen, open-source TTL and state-archival automation for Soroban.',
        ],
        tags: ['Soroban', 'Stellar'],
    },
    {
        id: 5,
        role: 'Lead',
        company: 'Superteam Campus Club UIN Bandung',
        location: 'Bandung, Indonesia',
        period: 'Feb 2026 — Present',
        description: [
            'Leads the Solana campus community: operations, shipping Web3 projects, and developer relations.',
        ],
        tags: ['Solana', 'DevRel'],
    },
    {
        id: 6,
        role: 'GRC Member',
        company: 'Wo-Men in Tech Security',
        location: 'Remote',
        period: 'Nov 2025 — Mar 2026',
        description: [
            'Assisted in audit preparation for ISO 27001 and SOC 2 by gathering and tagging technical evidence from IT teams.',
            'Monitored GRC automation platforms (Vanta, Drata) to identify and remediate non-compliant devices, achieving 100% policy adherence.',
            'Administered security awareness training with a 95%+ completion rate and maintained the central Risk Register.',
        ],
        tags: ['ISO 27001', 'SOC 2', 'Vanta', 'GRC'],
    },
    {
        id: 7,
        role: 'Full-Stack Engineer (Academic Collaboration)',
        company: 'Changlun Smart Agriculture System',
        location: 'Malaysia',
        period: 'Dec 2025',
        description: [
            'Architected a scalable SaaS platform for agricultural data management using Django (Python), focusing on backend logic and database schema optimization.',
            'Designed RESTful APIs to handle data ingestion from IoT sensors, ensuring data integrity and efficient query performance.',
            'Collaborated with Dr. Rohaya at UUM to translate agricultural domain requirements into technical system specifications.',
        ],
        tags: ['Django', 'Python', 'REST API', 'IoT'],
    },
    {
        id: 8,
        role: 'Security Consultant & Interim Lead',
        company: 'National Student Election System for CSSMoRA Indonesia',
        location: 'Remote',
        period: 'Nov 2025 — Dec 2025',
        description: [
            'Took over 24 hours before launch and pivoted to a serverless Google Apps Script solution.',
            'Engineered token-based unique-voter validation, with zero fraud incidents.',
        ],
        tags: ['Google Apps Script', 'Security'],
    },
    {
        id: 9,
        role: 'Technical Writer & Analyst',
        company: 'Ibunda.id',
        location: 'Bandung, Indonesia',
        period: 'Jun 2025 — Oct 2025',
        description: [
            'Developed detailed system documentation and role-specific user manuals for three core products using GitLab and Notion, reducing onboarding time.',
            'Conducted technical presentations on user sentiment analysis utilizing SVM algorithms, translating complex AI concepts into actionable insights.',
            'Documented API contracts and service boundaries within a microservices architecture to ensure clarity in inter-service communication.',
            'Monitored code quality via SonarQube and analyzed application logs in Grafana to proactively identify bug patterns.',
        ],
        tags: ['Technical Writing', 'SVM', 'SonarQube', 'Grafana'],
    },
    {
        id: 10,
        role: 'Front-End Engineer',
        company: 'StudentxCEOs Bandung Chapter',
        location: 'Bandung, Indonesia',
        period: 'Jan 2025 — Jun 2025',
        description: [
            'Developed UI components for six web pages including login and registration using Next.js and TypeScript.',
            'Resolved server-side rendering issues in Next.js that caused page load delays, optimizing component rendering for better performance.',
            'Collaborated with UI/UX designers and backend teams to ensure seamless integration and consistent user experience.',
        ],
        tags: ['Next.js', 'TypeScript', 'React', 'SSR'],
    },
    {
        id: 11,
        role: 'Founder & Developer',
        company: 'Focustudio.online',
        location: 'Remote',
        period: 'Oct 2024 — Present',
        description: [
            'Founded a personal web agency, managing client projects from development to deployment.',
            'Implemented CI/CD pipelines using Cloudflare Tunnel and GitHub Actions to automate deployment workflows.',
            'Ensured site reliability and continuous delivery through rigorous automation practices.',
        ],
        tags: ['CI/CD', 'GitHub Actions', 'Cloudflare'],
    },
    {
        id: 12,
        role: 'Technical Support Specialist & Virtual Coordinator',
        company: 'Indonesian Ministry of Religious Affairs (w/ LPDP)',
        location: 'Jakarta, Indonesia',
        period: 'Apr 2024 — Apr 2025',
        description: [
            'Managed end-to-end virtual infrastructure for national-level PBSB scholarship selection, facilitating interviews for hundreds of candidates.',
            'Orchestrated complex Zoom logistics including breakout rooms and secure access controls for government officials.',
        ],
        tags: ['Virtual Events', 'Zoom', 'Infrastructure'],
    },
];
